config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :usuarios
  root to: 'welcome#index'
  resources :certificados
  resources :recibos
  resources :grupos
  resources :cursos
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grupo.rb
class Grupo < ApplicationRecord
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]

  # GET /grupos
  # GET /grupos.json
  def index
    @grupos = Grupo.all
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: 'Grupo was successfully created.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:grup_id, :cur_id, :est_cedula, :doc_cedula)
    end
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_with(model: grupo, local: true) do |form| %>
  <% if grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'código del grupo' %>
    <%= form.number_field :grup_id %>
  </div>

  <div class="field">
    <%= form.label 'código del curso' %>
    <%= form.number_field :cur_id %>
  </div>

  <div class="field">
    <%= form.label 'cédula del estudiante' %>
    <%= form.number_field :est_cedula %>
  </div>

  <div class="field">
    <%= form.label 'cédula del docente' %>
    <%= form.number_field :doc_cedula %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editar Grupo</h1>

<%= render 'form', grupo: @grupo %>

<%= link_to 'Ver', @grupo %> |
<%= link_to 'Atrás', grupos_path %>

app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grupos</h1>

<table>
  <thead>
    <tr>
      <th>Grupo</th>
      <th>Curso</th>
      <th>Cedula estudiante</th>
      <th>Cedula docente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.grup_id %></td>
        <td><%= grupo.cur_id %></td>
        <td><%= grupo.est_cedula %></td>
        <td><%= grupo.doc_cedula %></td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo', new_grupo_path %>

app/views/grupos/new.html.erb
<h1>New Grupo</h1>

<%= render 'form', grupo: @grupo %>

<%= link_to 'Back', grupos_path %>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grup:</strong>
  <%= @grupo.grup_id %>
</p>

<p>
  <strong>Cur:</strong>
  <%= @grupo.cur_id %>
</p>

<p>
  <strong>Est cedula:</strong>
  <%= @grupo.est_cedula %>
</p>

<p>
  <strong>Doc cedula:</strong>
  <%= @grupo.doc_cedula %>
</p>

<%= link_to 'Editar', edit_grupo_path(@grupo) %> |
<%= link_to 'Atrás', grupos_path %>