config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :usuarios
  root to: 'welcome#index'
  resources :certificados
  resources :recibos
  resources :grupos
  resources :cursos
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/certificado.rb
class Certificado < ApplicationRecord
end

app/controllers/certificados_controller.rb
class CertificadosController < ApplicationController
  before_action :set_certificado, only: [:show, :edit, :update, :destroy]

  # GET /certificados
  # GET /certificados.json
  def index
    @certificados = Certificado.all
  end

  # GET /certificados/1
  # GET /certificados/1.json
  def show
  end

  # GET /certificados/new
  def new
    @certificado = Certificado.new
  end

  # GET /certificados/1/edit
  def edit
  end

  # POST /certificados
  # POST /certificados.json
  def create
    @certificado = Certificado.new(certificado_params)

    respond_to do |format|
      if @certificado.save
        format.html { redirect_to @certificado, notice: 'Certificado was successfully created.' }
        format.json { render :show, status: :created, location: @certificado }
      else
        format.html { render :new }
        format.json { render json: @certificado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificados/1
  # PATCH/PUT /certificados/1.json
  def update
    respond_to do |format|
      if @certificado.update(certificado_params)
        format.html { redirect_to @certificado, notice: 'Certificado was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificado }
      else
        format.html { render :edit }
        format.json { render json: @certificado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificados/1
  # DELETE /certificados/1.json
  def destroy
    @certificado.destroy
    respond_to do |format|
      format.html { redirect_to certificados_url, notice: 'Certificado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificado
      @certificado = Certificado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificado_params
      params.require(:certificado).permit(:cert_id, :cert_fechaexpedicion, :grup_id, :cur_id, :est_cedula, :doc_cedula)
    end
end

app/helpers/certificados_helper.rb
module CertificadosHelper
end

app/views/certificados/_form.html.erb
<%= form_with(model: certificado, local: true) do |form| %>
  <% if certificado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificado.errors.count, "error") %> prohibited this certificado from being saved:</h2>

      <ul>
      <% certificado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label 'Fecha de expedición' %>
    <%= form.date_select :cert_fechaexpedicion %>
  </div>

  <div class="field">
    <%= form.label 'número del grupo' %>
    <%= form.number_field :grup_id %>
  </div>

  <div class="field">
    <%= form.label 'código del curso' %>
    <%= form.number_field :cur_id %>
  </div>

  <div class="field">
    <%= form.label 'cédula del estudiante' %>
    <%= form.number_field :est_cedula %>
  </div>

  <div class="field">
    <%= form.label 'cédula del docente' %>
    <%= form.number_field :doc_cedula %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/certificados/edit.html.erb
<h1>Editar Certificado</h1>

<%= render 'form', certificado: @certificado %>

<%= link_to 'Ver', @certificado %> |
<%= link_to 'Atrás', certificados_path %>

app/views/certificados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Certificados</h1>

<table>
  <thead>
    <tr>
      <th>Cert</th>
      <th>Cert fechaexpedicion</th>
      <th>Grup</th>
      <th>Cur</th>
      <th>Est cedula</th>
      <th>Doc cedula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificados.each do |certificado| %>
      <tr>
        <td><%= certificado.cert_id %></td>
        <td><%= certificado.cert_fechaexpedicion %></td>
        <td><%= certificado.grup_id %></td>
        <td><%= certificado.cur_id %></td>
        <td><%= certificado.est_cedula %></td>
        <td><%= certificado.doc_cedula %></td>
        <td><%= link_to 'Show', certificado %></td>
        <td><%= link_to 'Edit', edit_certificado_path(certificado) %></td>
        <td><%= link_to 'Destroy', certificado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certificado', new_certificado_path %>

app/views/certificados/new.html.erb
<h1>New Certificado</h1>

<%= render 'form', certificado: @certificado %>

<%= link_to 'Atrás', certificados_path %>

app/views/certificados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cert:</strong>
  <%= @certificado.cert_id %>
</p>

<p>
  <strong>Cert fechaexpedicion:</strong>
  <%= @certificado.cert_fechaexpedicion %>
</p>

<p>
  <strong>Grup:</strong>
  <%= @certificado.grup_id %>
</p>

<p>
  <strong>Cur:</strong>
  <%= @certificado.cur_id %>
</p>

<p>
  <strong>Est cedula:</strong>
  <%= @certificado.est_cedula %>
</p>

<p>
  <strong>Doc cedula:</strong>
  <%= @certificado.doc_cedula %>
</p>

<%= link_to 'Edit', edit_certificado_path(@certificado) %> |
<%= link_to 'Back', certificados_path %>