config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :usuarios
  root to: 'welcome#index'
  resources :certificados
  resources :recibos
  resources :grupos
  resources :cursos
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel cun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="..">Hotel CUN</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="..">Inicio</a></li>
            <li><%= link_to ' Cursos', cursos_path, :class => 'navbar-link' %></li>
            <li><%= link_to ' Pagos', recibos_path, :class => 'navbar-link' %></li>
            <li><%= link_to ' Certificados', certificados_path, :class => 'navbar-link' %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text pull-right">
              <% if usuario_signed_in? %>
                <span class="glyphicon glyphicon-user"></span>Usuario:  <strong><%= current_usuario.nombre %></strong>.
                <%= link_to ' Editar usuario', edit_usuario_registration_path, :class => 'navbar-link' %> |
                <span class="glyphicon glyphicon-log-in"></span><%= link_to " cerrar sesión", destroy_usuario_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <span class="glyphicon glyphicon-user"></span><%= link_to " Nuevo usuario", new_usuario_registration_path, :class => 'navbar-link'  %> |
                <span class="glyphicon glyphicon-log-in"></span><%= link_to " Login", new_usuario_session_path, :class => 'navbar-link'  %>
              <% end %>
            </p>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </body>
</html>